### ISSUE TITLE
x11_in_qt5 ignores XWindow initial size

### ISSUE THREAD

**Issue by x42** [lv2/suil#14]
run
```
jalv.qt5 http://gareus.org/oss/lv2/tuna#one
```
The plugin calls XCreateWindow (...  517, 300, ...) and sets XSetNormalHints:

      Program supplied minimum size: 517 by 300
      Program supplied maximum size: 517 by 300

Yet jalv.qt5 brings up a window 200x100.

jalv.gtk, jalv.gtk3 work correctly and honor min/max and default size, jalv.qt4 has the correct default size (517x324 with jalv's menu bar) but does not enforce the size constraints.

Tested with gtk/qt on debian 10.3 with suil fbf5c739154e3a

**Comment by brummer10** [comment]
As Qt5 has removed X11 support there is no easy way to read  XSetNormalHints into a Qwidget.
Still it is possible to use  LV2UI_Resize to forward the size request to the Qwidget. 
But even then, it is needed to change line 113 from
`ew->resize(width, height);`
to
`ew->setMinimumSize(width, height);`
to make the Qwidget open with the requested size.

**Comment by drobilla** [comment]
I don't see how Qt supporting X11 makes any difference?

Suil has access to the X11 `Window` and can get information from it and do whatever it likes with it.

**Comment by brummer10** [comment]
Ah yes, I've forgotten that suil have the ID. 
So, nice to hear that you could easily fix it.

**Comment by drobilla** [comment]
eee62b7f32e4ef7aaca09565fa53b54ad0815970

Also 7b728fc201269cfcad91ad4d9fdcd949483c3485 which implements resize (eliminating at least half of the reason for the resize kludge extension).

**Comment by x42** [comment]
Cheers!
