### ISSUE TITLE
QT5 in QT5

### ISSUE THREAD

**Issue by hoshinetop** [lv2/suil#15]
Hey,
I'm wondering if I understand the thing correctly.
I want to run a QT5 plugin UI inside of an embedded QT5 application (running with EGLFS). Does that mean that I need to have a qt5_in_qt5 wrapper which doesn't exist yet?
As a particular example, I want to run fil4.lv2 EQ plugin's UI inside Carla running as a standalone EGLFS app. Carla seems to be able to run like EGLFS app, but that rich fil4.lv2's UI doesn't open.
Thanks.

**Comment by drobilla** [comment]
I don't really know anything about EGLFS, but no, you don't need a wrapper to "do nothing".  Suil will automatically just pass through the UI widget if it matches the type of the host.

**Comment by hoshinetop** [comment]
Actually that doesn't seem correct. Pure EGLFS doesn't have any window manager and suil calls specific functions to create an application window. So it doesn't work with pure EGLFS because it lacks any window management. My current solution is to add Wayland + Xwayland... Anyway, thanks.

**Comment by drobilla** [comment]
> suil calls specific functions to create an application window

Where do you get that idea?  Suil doesn't even link against any graphics libraries whatsoever in the pass-through case, so it couldn't possibly be calling functions to create windows.

**Comment by hoshinetop** [comment]
Looks like a debug mess in my head. The above seems to be true about fil4.lv2 code, not about suil. fil4.lv2 has OSX, Win or X11. At some point I was trying to work it around and has gone into the suil code.
