### ISSUE TITLE
Unable to wrap UI type

### ISSUE THREAD

**Issue by evertvorster** [lv2/suil#20]
I am building audacity against system libraries on Arch linux.
When audacity tries to display a UI of a plugin, the following error pops up in the console, and no UI pops up. 

suil error: Unable to wrap UI type <http://lv2plug.in/ns/extensions/ui#GtkUI> as type <http://lv2plug.in/ns/extensions/ui#Gtk3UI>

How do I go about finding out more about this error? What are the possible reasons that it pops up? I have been blaming wxWidgets so far, but I am starting to have my doubts as I have been trying various versions of wxWidgets, and always get the same error.

**Comment by drobilla** [comment]
It is unfortunately not possible to embed Gtk2 in Gtk3.  If you want such UIs to work in a Gtk3 host, they'll need to be shown in a separate window managed by a separate process that communicates with the main one via IPC.  Suil currently does not have magic support for such situations (although arguably it should, and a future major version might).

In general the LV2 world is trying to get away from Gtk plugin UIs for this reason (among others).  It's just not suitable for plugin UIs that might be embedded in a different toolkit, or different major versions of Gtk itself.
