### ISSUE TITLE
Improper handling of nested plugin window size

### ISSUE THREAD

**Issue by sadko4u** [lv2/suil#22]
Hi!

Look at Ardour that can not handle the size change of the window when the plugin's UI is an initiator of such change:

https://www.youtube.com/watch?v=iSFl7B3itsI

Other formats like VST2, VST3 and CLAP perform pretty fine because they have well-designed UI resize API.
By the other side, LV2 doesn't provide good way of changing window size of the plugin (we don't count the lv2:resize which is considered to be a bad solution).

**Comment by x42** [comment]
Since this works well for other LV2 plugins, and libsuil just wraps the X11 window passing events this looks like an issue with the plugin GUI. More evidence for that is that you can resize the wrapped window directly as seen at 0:35.

**Comment by drobilla** [comment]
b2c64e5 tracks X11 window size changes in the child window for Gtk3.  That doesn't apply to Ardour (which is using a fork now anyway), but a similar change might work in Gtk2.  The size model is different though and I haven't bothered.  It can be tested with jalv.gtk3, the scaling buttons on current LSP plugins increase the window size (and its minimum), etc.

The window doesn't shrink there, although that case is a bit weird and I'm not sure if it can/should.  Ultimately the hints are the important thing though, as long as those are set sensibly things should work more or less reasonably.

I think the `XSelectInput` part is the magic that was missing in previous attempts at this.  With `SubstructureRedirectMask` events you can get configure and map events for the child and do whatever with that information.
