### ISSUE TITLE
Build fail after upgrade 0.10.0 -> 0.10.2

### ISSUE THREAD

**Issue by schnitzeltony** [lv2/suil#6]
After update I get (no build option set  / default)

| Waf: Entering directory `/home/superandy/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-mortsgna-linux-gnueabi/suil/0.10.2-r0/build'
| [ 1/19] Compiling src/instance.c
| [ 2/19] Compiling src/host.c
| [ 3/19] Compiling src/gtk2_in_qt5.cpp
| [ 4/19] Compiling src/qt5_in_gtk2.cpp
| [ 5/19] Compiling src/x11_in_gtk2.c
| [ 6/19] Compiling src/x11_in_gtk3.c
| [ 7/19] Compiling src/x11_in_qt5.cpp
| [ 8/19] Compiling src/cocoa_in_qt5.mm
| arm-mortsgna-linux-gnueabi-g++: error: ../suil-0.10.2/src/cocoa_in_qt5.mm: Objective-C++ compiler not installed on this system
| 
| Waf: Leaving directory `/home/superandy/tmp/oe-core-glibc/work/cortexa7t2hf-neon-vfpv4-mortsgna-linux-gnueabi/suil/0.10.2-r0/build'

Looks to me some waf magic is going on..

**Comment by schnitzeltony** [comment]
Looked into this. In my build environment (Openembedded/Yocto) there is the file QMacCocoaViewContainer installed - although building on and for Linux only. Seems checking for QMacCocoaViewContainer only is not good enough (at least for me).

FWIW: My builds could be fixed by patch attached - but that is surely nothing to upstream here
[0001-Do-not-try-to-build-macOS-cocoa.txt](https://github.com/drobilla/suil/files/2710913/0001-Do-not-try-to-build-macOS-cocoa.txt)

**Comment by drobilla** [comment]
Hm.  I am confused.  How/why do you have QMacCocoaViewContainer on a non-Mac?  I suppose I could put an explicit platform check around this or something, but this can be problematic for cross-compiling and such, so I'd rather not work around it if it's just a botched build host.

**Comment by schnitzeltony** [comment]
Good question - how QMacCocoaViewContainer made it into installation - maybe there is something wrong with our qtbase. 

Suggestion: 

1. We close this one 
2. As soon as other packagers on more common environments complain for same it might be time to think about further checks.

**Comment by drobilla** [comment]
Sure.  We'll see...

Thanks for the report
